# Generated by Django 5.1.3 on 2025-05-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_condition', models.CharField(max_length=255)),
                ('chief_complaint', models.TextField()),
                ('blood_pressure', models.CharField(max_length=255)),
                ('pulse', models.CharField(max_length=255)),
                ('temperature', models.CharField(max_length=255)),
                ('heart', models.CharField(max_length=255)),
                ('lungs', models.CharField(max_length=255)),
                ('abdomen', models.CharField(max_length=255)),
                ('anaemia', models.CharField(max_length=255)),
                ('jaundice', models.CharField(max_length=255)),
                ('cyanosis', models.CharField(max_length=255)),
                ('oedema', models.CharField(max_length=255)),
                ('past_history', models.TextField()),
                ('present_history', models.TextField()),
                ('drug_history', models.TextField()),
                ('class_type', models.CharField(max_length=255)),
                ('ideal_weight', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('height_feet', models.FloatField()),
                ('height_inch', models.FloatField()),
                ('bmi', models.FloatField()),
                ('insulin', models.CharField(max_length=255)),
                ('z_score', models.CharField(max_length=255)),
                ('bmr', models.CharField(max_length=255)),
                ('edd', models.CharField(max_length=255)),
                ('last_visit', models.CharField(max_length=255)),
                ('paid_amount', models.FloatField()),
            ],
        ),
    ]
