# Generated by Django 5.1.3 on 2025-05-02 06:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='address',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='prescription',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='cc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prescription',
            name='disease',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='ix',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='mobile',
            field=models.CharField(default='Unknown', max_length=15),
        ),
        migrations.AddField(
            model_name='prescription',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='oe',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='reg_no',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='prescription',
            name='sex',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='abdomen',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='anaemia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='bmr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='chief_complaint',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='class_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='cyanosis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='disease_condition',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='drug_history',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='edd',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='heart',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='height_feet',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='height_inch',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='ideal_weight',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='insulin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='jaundice',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='last_visit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='lungs',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='oedema',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='paid_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='past_history',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='present_history',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='pulse',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='temperature',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='z_score',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
