# Generated by Django 5.2 on 2025-05-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0002_prescription_address_prescription_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.TextField(blank=True),
        ),
    ]
