# Generated by Django 5.1.3 on 2025-05-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_prescription_medicines'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('footer_text', models.TextField(blank=True)),
                ('show_barcode', models.BooleanField(default=True)),
            ],
        ),
    ]
