# Generated by Django 5.1.3 on 2025-05-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0004_headerfooter'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('drug', 'Drug'), ('advice', 'Advice'), ('treatment', 'Treatment'), ('cc', 'C/C'), ('oe', 'O/E'), ('ix', 'I/X')], max_length=20)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
    ]
